### ISSUE TITLE
opencore sleep wake up

### ISSUE THREAD

**Issue by erdalceylan** [linhnguyengas/Hackintosh-Acer-Swift3-SF315-52G#3]
hi @linhnguyengas how did you sleep and wake up fix does not work me

**Comment by linhnguyen-gt** [comment]
> hi @linhnguyengas how did you sleep and wake up fix does not work me

sorry I'm late reply 
I checked it 
you can reinstall OpenCore and enjoy sleep-wake up :)
remember reset NVRAM
