### ISSUE TITLE
ALC256 Internal Mic

### ISSUE THREAD

**Issue by abdllhcrk** [linhnguyengas/Hackintosh-Acer-Swift3-SF315-52G#4]
hey, thanks for sharing your precious project with. I wanna ask about current situation of internal mic. Did you make any progress ?

**Comment by linhnguyen-gt** [comment]
> hey, thanks for sharing your precious project with. I wanna ask about current situation of internal mic. Did you make any progress ?

currently mic not working, I don't know how to fix it. You can use mic with Bluetooth connection AirPods.

**Comment by abdllhcrk** [comment]
> > hey, thanks for sharing your precious project with. I wanna ask about current situation of internal mic. Did you make any progress ?
> 
> 
> 
> currently mic not working, I don't know how to fix it. You can use mic with Bluetooth connection AirPods.

When I use Airpods' Mic, quality is really bad. Do you have the problem?

**Comment by linhnguyengas** [comment]
Me too

**Comment by linhnguyen-gt** [comment]
Me too
