### ISSUE TITLE
Facing Issues of Screen Flickering While Using and only 13inch screen after sleep

### ISSUE THREAD

**Issue by AirDronzer** [linhnguyengas/Hackintosh-Acer-Swift3-SF315-52G#5]
Hy Buddy thanks for ur wonderful work i had some issues with ur EFI Opencore 0.6.5 like screen flickering while using and 13 inch screen after wake from sleep and I have solutions for mic if u could try with layout 66 I found one guy on reddit using this layout on Acer Swift 3 his mic was working and another solution is to try with ALCPlugins.

It Would be Greatful if u solve these issues for me.

Thanks For Everything :).

**Comment by linhnguyen-gt** [comment]
thank you for your solution but my mic it still doesn't work 😂
your problem after sleep 
do you have to use one key hidpi and set display scaled 1680x944?
if you do it, one key hidpi just support 1424x802 HiDPI resolution, to enable higher HiDPI resolution (<=1520x855), you need to set DVMT to 64mb
Currently, I don't know how to activate it on Swift 3
