### ISSUE TITLE
I want to donate to you, any method?

### ISSUE THREAD

**Issue by bsthun** [linhnguyengas/Hackintosh-Acer-Swift3-SF315-52G#8]
I really love your project. The OC EFI helps me a lot in hackintoshing my notebook that I have tried for a long time and just get my job done because of your repo. So I just want to donate a paltry as a thank you gift from me. If you have any method (paypal, buy me a coffee or something), please tell me.

**Comment by linhnguyen-gt** [comment]
thank you for that 
please  buy me a coffee or breakfast  https://www.paypal.com/paypalme/nguyenlinhgt
I would be very grateful for that 😊

**Comment by BSthun** [comment]
Okay. I've sent it to you! Please check out for that. And lastly, thank you so much for the EFI.
<img width="398" alt="Screen Shot 2564-03-16 at 8 29 10 AM" src="https://user-images.githubusercontent.com/28301483/111242401-b0a42900-8631-11eb-837c-b1112cf907c9.png">

**Comment by bsthun** [comment]
Okay. I've sent it to you! Please check out for that. And lastly, thank you so much for the EFI.
<img width="398" alt="Screen Shot 2564-03-16 at 8 29 10 AM" src="https://user-images.githubusercontent.com/28301483/111242401-b0a42900-8631-11eb-837c-b1112cf907c9.png">
